version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Specify your Node.js version
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the code...
      - npm run build
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  discard-paths: no 
